name: 'Source Map Compile'
description: 'Compile source maps'
inputs:
  game:
    description: 'Name of the game'
    required: false
    default: 'csgo' #Default CS:GO
  gameid:
    description: 'AppId of the game'
    required: false
    default: '730' #Default CS:GO
  sdkid:
    description: 'AppId of the game sdk'
    required: false
    default: '745' #Default CS:GO SDK
  map:
    description: '.vmf to be compiled'
    required: true
  vbspargs:
    description: 'Additional vbsp.exe arguments'
    required: false
    default: ''
  vvisargs:
    description: 'Additional vvis.exe arguments'
    required: false
    default: ''
  vradargs:
    description: 'Additional vrad.exe arguments'
    required: false
    default: '-both -final -textureshadows -StaticPropLighting -StaticPropPolys'
  username:
    description: 'Steam account username'
    required: false
    default: ''
  password:
    description: 'Steam account password'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - uses: "Skippeh/steamfetch-action@v1.0.3"
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        dir: "${{ github.workspace }}/game_files/"
        os: "windows"
        app: ${{ inputs.gameid }}
        depot: 732 #Workaround till https://github.com/SteamRE/DepotDownloader/issues/222 is a thing
        osarch: 64
    - uses: "Skippeh/steamfetch-action@v1.0.3"
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        dir: "${{ github.workspace }}/game_files/"
        os: "windows"
        app: ${{ inputs.gameid }}
        depot: 731
        osarch: 64
    - uses: "Skippeh/steamfetch-action@v1.0.3"
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        dir: "C:\\game_files\\"
        os: "windows"
        app: ${{ inputs.sdkid }}
        osarch: 64
    - run: "C:\\game_files\\bin\\vbsp.exe ${{ inputs.vbspargs }} -game C:\\game_files\\${{ inputs.game }} ${{ inputs.map }}"
    - run: "C:\\game_files\\bin\\vvis.exe ${{ inputs.vvisargs }} -game C:\\game_files\\${{ inputs.game }} ${{ inputs.map }}"
    - run: "C:\\game_files\\bin\\vrad.exe ${{ inputs.vradargs }} -game C:\\game_files\\${{ inputs.game }} ${{ inputs.map }}"
